---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: springboot-k
  namespace: flux-system
spec:
  interval: 5m0s
  path: app/springboot
  prune: true
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nodejs-k
  namespace: flux-system
spec:
  interval: 5m0s
  path: app/nodejs
  prune: true
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dotnetcore-k
  namespace: flux-system
spec:
  interval: 5m0s
  path: app/dotnetcore
  prune: true
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  validation: client

