---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kpack-awesome-demo
  namespace: flux-system
spec:
  interval: 1s
  ref:
    branch: main
  url: https://github.com/bmoussaud/kpack-awesome-demo
  secretRef:
    name: https-github-credentials 
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: kpack-awesome-demo-automation
  namespace: flux-system
spec:
  interval: 1s
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: bmoussaud@users.noreply.github.com
        name: bmoussaud
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./clusters/aws-tools
    strategy: Setters
