---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kpack-awesome-demo
  namespace: flux-system
spec:
  interval: 11s
  ref:
    branch: main
  url: https://github.com/bmoussaud/kpack-awesome-demo.git

