apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: nodejs-image-repository
  namespace: flux-system
spec:
  image: harbor.mytanzu.xyz/library/cnb-nodejs
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: nodejs-harbor-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-image-repository
  filterTags:
    pattern: '^b(\d*).(?P<ts>\d\d\d\d\d\d\d\d.\d\d\d\d\d\d)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nodejs-k
  namespace: flux-system
spec:
  interval: 10s
  path: app/nodejs
  prune: true
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  validation: client
  images:
    - name: alexandreroman/cnb-nodejs
      newName: harbor.mytanzu.xyz/library/cnb-nodejs # {"$imagepolicy": "flux-system:nodejs-harbor-policy:name"}
      newTag: b24.20210812.015154 # {"$imagepolicy": "flux-system:nodejs-harbor-policy:tag"}
