apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: springboot-image-repository
  namespace: flux-system
spec:
  image: harbor.mytanzu.xyz/library/cnb-springboot
  interval: 1s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: springboot-harbor-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: springboot-image-repository
  filterTags:
    pattern: '^b(\d*).(?P<ts>\d\d\d\d\d\d\d\d.\d\d\d\d\d\d)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: springboot-k
  namespace: flux-system
spec:
  interval: 1s
  path: app/springboot
  prune: true
  sourceRef:
    kind: GitRepository
    name: kpack-awesome-demo
  validation: client
  images:
    - name: alexandreroman/cnb-springboot
      newName: harbor.mytanzu.xyz/library/cnb-springboot # {"$imagepolicy": "flux-system:springboot-harbor-policy:name"}
      newTag: b829.20210916.171530 # {"$imagepolicy": "flux-system:springboot-harbor-policy:tag"}
