---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: awesomedemo-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java:5.9.1
  #- image: gcr.io/paketo-buildpacks/java:5.8.0
  - image: gcr.io/paketo-buildpacks/go
  - image: gcr.io/paketo-buildpacks/nodejs
  - image: gcr.io/paketo-buildpacks/dotnet-core
  - image: gcr.io/paketo-buildpacks/spring-boot  
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: yetanother-store
spec:
  sources:
  #- image: gcr.io/paketo-buildpacks/java:5.9.1
  - image: gcr.io/paketo-buildpacks/java:5.8.0
  - image: gcr.io/paketo-buildpacks/go
  - image: gcr.io/paketo-buildpacks/nodejs
  - image: gcr.io/paketo-buildpacks/dotnet-core
  - image: gcr.io/paketo-buildpacks/spring-boot
  #- image: gcr.io/paketo-buildpacks/image-labels  not necessary to add it, it should be included ...
  #- image: harbor.mytanzu.xyz/library/owner-buildpack:0.0.3
  
