---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind:  
metadata:
  name: springboot-image-repository
  namespace: flux-system
spec:
  interval: 1m0s
  image: harbor.mytanzu.xyz/library/cnb-springboot
  secretRef:
    name: harbor-service-account
    namespace: kpack
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: springoot-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: springboot-image-repository
--

