apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: dotnetcore-builder  
spec:
  serviceAccount: awesomedemo-account
  tag: harbor.mytanzu.xyz/library/dotnetcore-builder
  stack:
    name: bawesomedemoase
    kind: ClusterStack
  store:
    name: yetanother-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/image-labels

  