apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: dotnetcore-builder  
spec:
  serviceAccount: harbor-service-account
  tag: harbor.mytanzu.xyz/library/dotnetcore-builder
  stack:
    name: full
    kind: ClusterStack
  store:
    name: default-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/dotnet-core

  