apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-dotnetcore-image
spec:
  tag: harbor.mytanzu.xyz/library/cnb-dotnetcore  
  serviceAccountName: awesomedemo-account
  builder:
    name: dotnetcore-builder
    kind: Builder
  failedBuildHistoryLimit: 2
  successBuildHistoryLimit: 2
  source:
    git:
      url: https://github.com/bmoussaud/cnb-dotnetcore
      revision: main
  build: # Optional
    env:
      - name: BP_IMAGE_LABELS
        value: kpack.builder.project=dotnetcore kpack.builder.instance=tbs-2 kpack.builder.author=benoitmoussaud
