apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: springboot-builder
spec:
  serviceAccount: awesomedemo-account
  tag: harbor.mytanzu.xyz/library/springboot-builder
  stack:
    name: awesomedemo-stack
    kind: ClusterStack
  store:
    name: awesomedemo-store-v1
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
      version: 5.5.0
---
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: springboot-builder-11.0.10
spec:
  serviceAccount: awesomedemo-account
  tag: harbor.mytanzu.xyz/library/springboot-builder
  stack:
    name: awesomedemo-stack
    kind: ClusterStack
  store:
    name: awesomedemo-store-v1
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
      version: 5.5.0
---
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: springboot-builder-11.0.12
spec:
  serviceAccount: awesomedemo-account
  tag: harbor.mytanzu.xyz/library/springboot-builder
  stack:
    name: awesomedemo-stack
    kind: ClusterStack
  store:
    name: awesomedemo-store-v2
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
      version: 5.13.0

  