apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: cnb-springboot-image
spec:
  tag: harbor.mytanzu.xyz/library/cnb-springboot
  serviceAccountName: awesomedemo-account
  builder:
    name: springboot-builder-11.0.10
    kind: Builder
  failedBuildHistoryLimit: 2
  successBuildHistoryLimit: 2
  source:
    git:
      url: https://github.com/bmoussaud/cnb-springboot
      revision: master
  build: # Optional
    env:
      - name: BP_IMAGE_LABELS
        value: kpack.builder.project=springboot kpack.builder.instance=tbs-2 kpack.builder.author=benoitmoussaud
      #- name: BP_JVM_VERSION
      #  value: "16"
