apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-nodejs-image
spec:
  tag: harbor.mytanzu.xyz/library/cnb-nodejs
  serviceAccount: harbor-service-account
  builder:
    name: node-builder
    kind: Builder
  source:
    git:
      url: https://github.com/bmoussaud/cnb-nodejs
      revision: master