# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-namespace.yml
- 02-deployment.yml
- 03-service.yml
- 04-ingress.yml
namespace: cnb-dotnetcore
images:
  - name: bmoussaud/cnb-dotnetcore
    newName: harbor.mytanzu.xyz/library/cnb-dotnet-core