apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: node-builder    
spec:
  serviceAccount: harbor-service-account
  tag: harbor.mytanzu.xyz/library/node-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: yetanother-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs      
    - id: mycompany/owner
      version: 0.0.2
    
   
  
  
  

  