apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: nodejs-builder    
spec:
  serviceAccount: awesomedemo-account
  tag: harbor.mytanzu.xyz/library/node-builder
  stack:
    name: awesomedemo-stack
    kind: ClusterStack
  store:
    name: yetanother-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs
    #- id: mycompany/owner
    #  version: 0.0.3
    #- id: paketo-buildpacks/image-labels
