apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-nodejs-image
spec:
  tag: harbor.mytanzu.xyz/library/cnb-nodejs
  serviceAccount: harbor-service-account
  builder:
    name: node-builder
    kind: Builder
  source:
    git:
      url: https://github.com/bmoussaud/cnb-nodejs
      revision: master
  build: # Optional
    env:
      - name: BP_IMAGE_LABELS
        value: kpack.builder.hostname=gimmick3 kpack.builder.instance=tbs-2
