apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: cnb-nodejs-image
spec:
  tag: harbor.mytanzu.xyz/library/cnb-nodejs
  serviceAccountName: awesomedemo-account
  builder:
    name: nodejs-builder
    kind: Builder
  failedBuildHistoryLimit: 2
  successBuildHistoryLimit: 2
  source:
    git:
      url: https://github.com/bmoussaud/cnb-nodejs
      revision: master
  build: # Optional
    env:
      - name: BP_IMAGE_LABELS
        value: kpack.builder.project=nodejs kpack.builder.instance=tbs-2 kpack.builder.author=benoitmoussaud
